---
- name: Destruir Infraestrutura na AWS
  hosts: localhost
  connection: local
  tasks:
    - name: 1. Baixar o arquivo ZIP do Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.9.0/terraform_1.9.0_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: 1.1 Extrair o ZIP usando o Python nativo
      shell: python3 -m zipfile -e /tmp/terraform.zip /tmp/

    - name: 1.2 Dar permissao de execucao ao binario
      file:
        path: /tmp/terraform
        mode: '0755'

    - name: 2. Inicializar o Terraform (init)
      command: /tmp/terraform init
      args:
        chdir: "{{ playbook_dir }}/infra"

    - name: 3. Destruir a Infraestrutura na AWS (destroy)
      command: /tmp/terraform destroy -auto-approve
      args:
        chdir: "{{ playbook_dir }}/infra"
      environment:
        AWS_ACCESS_KEY_ID: "{{ minha_chave_aws }}"
        AWS_SECRET_ACCESS_KEY: "{{ meu_segredo_aws }}"
        AWS_DEFAULT_REGION: "us-east-1"
